// Auto-generated by scripts/job_digest/podcasts/summarise.py — do not edit by hand.
export const PODCAST_DIGESTS = [
  {
    "episode_number": "ep047",
    "show": "Lenny's Podcast",
    "title": "Unconventional product lessons from Binance, N26, Google, more | Mayur Kamat (CPO at N26)",
    "guest": "Mayur Kamat",
    "published": "2024-03-01",
    "duration": "1.0h 37.0m",
    "topics": [
      "product",
      "cpo",
      "data"
    ],
    "relevance_score": 3,
    "youtube_url": "https://www.youtube.com/watch?v=UVyfuSBwbNA",
    "spotify_url": "",
    "apple_url": "",
    "summary": {
      "headline": "Mayur Kamat, CPO at N26, shares lessons on product management and career growth from his experiences at Binance, Google, and other companies",
      "key_takeaways": [
        "Focus on finding companies that are growing fast to compound your learning",
        "Optimize for your strengths and find jobs that utilize them",
        "Don't prioritize compensation early in your career, instead focus on learning and fun"
      ],
      "use_cases": [
        "Working at Binance with a flat structure and extreme ownership culture",
        "Solving complex problems like onboarding and KYC flows across multiple countries"
      ],
      "apply_to_prep": "As someone with experience in FinTech and product management, I can apply Mayur's advice on optimizing for strengths and finding companies with high compounding learning to my own career, particularly in my current role at N26 or in future roles like the ones I'm interviewing for, such as Senior PM or Head-of-FinCrime-Product",
      "framework_tags": [
        "career development",
        "product management",
        "growth mindset"
      ]
    }
  }
];
