SEARCH_KEYWORDS = [
    "senior product manager financial crime",
    "fincrime product manager",
    "product manager fincrime",
    "product manager kyc kyb",
    "product manager customer risk",
    "product compliance manager kyc",
    "senior product compliance manager kyc",
    "product compliance manager onboarding",
    "product compliance lead financial crime",
    "fenergo product owner",
    "fenx product owner",
    "client lifecycle management product owner",
    "kyc systems product owner",
    "name screening product manager",
    "payment screening product manager",
    "sanctions screening product manager",
    "aml platform product manager",
    "compliance automation product manager",
    "case management product manager",
    "financial crime senior manager systems controls",
    "head of kyc transformation",
    "head of onboarding transformation",
    "head of financial crime operations transformation",
    "financial crime transformation lead",
    "financial crime transformation contract",
    "1lod controls transformation lead",
    "payments compliance product manager",
    "payment risk product manager",
    "partner onboarding product manager",
    "merchant onboarding product manager",
    "kyc business analyst inside ir35",
    "clm business analyst inside ir35",
    "client onboarding transformation contract",
    "product manager kyc",
    "product manager aml",
    "product manager onboarding",
    "product manager screening",
    "product manager financial crime",
    "product manager compliance",
    "product manager identity",
    "product manager fraud",
    "product manager regtech",
    "product manager kyb",
    "product manager cdd",
    "product manager edd",
    "product owner kyc",
    "product owner onboarding",
    "product owner compliance",
    "product owner screening",
    "product manager transaction monitoring",
    "product manager client onboarding",
    "product manager customer onboarding",
    "product manager account opening",
    "product manager client lifecycle",
    "product manager customer lifecycle",
    "product manager clm",
    "product lead risk",
    "product lead compliance",
    "product manager sanctions",
    "product manager due diligence",
    "product manager case management",
    "product manager investigation",
    "product manager fraud prevention",
    "product manager identity verification",
    "product manager onboarding platform",
    "product manager compliance platform",
    "product manager risk platform",
    "product manager screening platform",
    "product manager financial crime platform",
    "client lifecycle management",
    "client lifecycle manager",
    "customer lifecycle management",
    "clm manager",
    "client lifecycle operations",
    "client lifecycle operations lead",
    "customer lifecycle operations",
    "customer lifecycle operations lead",
    "client lifecycle product",
    "customer lifecycle product",
    "onboarding operations",
    "onboarding operations lead",
    "client onboarding operations",
    "customer onboarding operations",
    "operations strategy",
    "operations strategy manager",
    "operations strategy lead",
    "operating model",
    "operating model design",
    "operating model manager",
    "operating model lead",
    "process owner",
    "customer onboarding lead",
    "client onboarding lead",
    "kyc operations lead",
    "aml operations lead",
    "compliance operations lead",
    "financial crime operations",
    "financial crime operations manager",
    "risk operations manager",
    "regulatory operations manager",
    "business analyst kyc",
    "business analyst aml",
    "business analyst onboarding",
    "business analyst compliance",
    "business analyst financial crime",
    "lead business analyst",
    "senior business analyst",
    "principal business analyst",
    "product business analyst",
    "process owner onboarding",
    "process owner kyc",
    "process owner compliance",
    "client lifecycle analyst",
    "customer lifecycle analyst",
    "clm product manager",
    "clm business analyst",
    "client lifecycle lead",
    "customer lifecycle lead",
    "lead business analyst onboarding",
    "lead business analyst financial crime",
    "business analyst screening",
    "business analyst sanctions",
    "business analyst client lifecycle",
    "business analyst customer lifecycle",
    "senior manager operations strategy",
    "operations strategy financial crime",
    "financial crime transformation",
    "financial crime transformation manager",
    "regulatory transformation manager",
    "onboarding transformation manager",
    "product operations manager",
    "product manager risk fraud",
    "product manager banking capital markets",
    "product manager alternative payment methods",
    "product manager aml screening",
    "payment product management",
    "head of product insurance",
    "senior product manager fraud risk",
    "staff product manager payments",
    "chainlink labs product manager",
    "checkout.com staff product manager",
    "napier ai product manager",
    "x4 technology senior product manager",
    "fiserv product manager risk fraud",
    "ki head of product",
]

BOARD_KEYWORDS = [
    "senior product manager financial crime",
    "financial crime product manager",
    "fincrime product manager",
    "product manager kyc kyb",
    "product compliance manager kyc",
    "senior product compliance manager kyc",
    "fenergo product owner",
    "fenx product owner",
    "client lifecycle management product owner",
    "kyc systems product owner",
    "sanctions screening product manager",
    "payment screening product manager",
    "aml platform product manager",
    "financial crime senior manager systems controls",
    "head of kyc transformation",
    "head of onboarding transformation",
    "financial crime transformation lead",
    "1lod controls transformation lead",
    "payments compliance product manager",
    "payment risk product manager",
    "kyc business analyst inside ir35",
    "clm business analyst inside ir35",
    "client onboarding transformation contract",
    "product manager onboarding",
    "product manager kyc",
    "product manager aml",
    "product manager compliance",
    "product manager screening",
    "product owner onboarding",
    "product manager fraud",
    "product manager financial crime",
    "client lifecycle management",
    "customer lifecycle management",
    "operations strategy",
    "onboarding operations",
    "client onboarding operations",
    "customer onboarding operations",
    "process owner",
    "operating model",
    "business analyst kyc",
    "business analyst onboarding",
    "lead business analyst",
    "process owner onboarding",
    "business analyst sanctions",
    "business analyst client lifecycle",
    "operations strategy financial crime",
    "financial crime transformation",
]

BROAD_BOARD_KEYWORDS = [
    "head of kyc transformation",
    "head of onboarding transformation",
    "head of financial crime operations transformation",
    "financial crime senior manager systems controls",
    "financial crime transformation lead",
    "kyc transformation lead",
    "clm transformation lead",
    "aml transformation lead",
    "1lod controls transformation lead",
    "payments compliance product manager",
    "payment risk product manager",
    "partner onboarding product manager",
    "merchant onboarding product manager",
    "kyc business analyst inside ir35",
    "clm business analyst inside ir35",
    "client onboarding transformation contract",
    "product manager",
    "product owner",
    "product lead",
    "product director",
    "product operations",
    "operations strategy",
    "onboarding operations",
    "client onboarding operations",
    "customer onboarding operations",
    "operating model",
    "process owner",
    "client lifecycle manager",
    "customer lifecycle manager",
    "business analyst",
    "lead business analyst",
    "senior business analyst",
    "business analyst sanctions",
    "business analyst client lifecycle",
    "clm business analyst",
    "financial crime transformation",
    "product operations manager",
    "process owner",
]

COMPANY_SEARCH_TERMS = [
    "senior product manager financial crime",
    "financial crime product manager",
    "product compliance manager kyc",
    "fenergo product owner",
    "fenx product owner",
    "sanctions screening product manager",
    "financial crime transformation",
    "kyc transformation",
    "clm transformation",
    "client onboarding transformation",
    "business analyst inside ir35",
    "product manager",
    "product owner",
    "product lead",
    "product manager onboarding",
    "product manager compliance",
    "product manager risk",
    "product manager fraud",
    "product management",
    "product operations",
    "product specialist",
    "client lifecycle",
    "customer lifecycle",
    "clm",
    "client lifecycle management",
    "customer lifecycle management",
    "onboarding operations",
    "client onboarding operations",
    "customer onboarding operations",
    "operations strategy",
    "operating model",
    "process owner",
    "financial crime operations",
    "compliance operations",
    "business analyst",
    "lead business analyst",
    "senior business analyst",
    "principal business analyst",
    "business analyst sanctions",
    "business analyst client lifecycle",
    "clm business analyst",
    "financial crime transformation",
    "product operations manager",
    "process owner",
]

SEARCH_COMPANIES = [
    # Banks & FS
    "Barclays",
    "HSBC",
    "NatWest",
    "Lloyds",
    "Lloyds Banking Group",
    "Santander",
    "Nationwide",
    "TSB",
    "Virgin Money",
    "Metro Bank",
    "Tesco Bank",
    "Coutts",
    "Standard Chartered",
    "Citi",
    "JPMorgan Chase & Co",
    "Goldman Sachs",
    "Morgan Stanley",
    "Bank of America",
    "Deutsche Bank",
    "UBS",
    "BNP Paribas",
    "Société Générale",
    "Societe Generale",
    "Crédit Agricole",
    "Credit Agricole",
    "RBC",
    "ING",
    "Rabobank",
    "ABN AMRO",
    "UniCredit",
    "BNY Mellon",
    "State Street",
    "Northern Trust",
    "BlackRock",
    "Vanguard",
    "Fidelity",
    "Nomura",
    "Mizuho",
    "MUFG",
    "SMBC",
    "Macquarie",
    "Jefferies",
    "Rothschild",
    "LSEG",
    # Fintech / Payments
    "Wise",
    "Revolut",
    "Monzo",
    "Starling",
    "Engine by Starling",
    "Tide",
    "Zopa",
    "OakNorth",
    "Atom Bank",
    "ClearBank",
    "Kroo",
    "Chip",
    "Curve",
    "Checkout.com",
    "Stripe",
    "Adyen",
    "Worldpay",
    "GoCardless",
    "Modulr",
    "TrueLayer",
    "Tink",
    "Plaid",
    "Airwallex",
    "Rapyd",
    "Marqeta",
    "Mambu",
    "Thought Machine",
    "Temenos",
    "Avaloq",
    "Funding Circle",
    "Lendable",
    "Zilch",
    "Solaris",
    "Soldo",
    "Pleo",
    "Yapily",
    "PayPal",
    "Block",
    "Square",
    # RegTech / KYC / Screening
    "Fenergo",
    "Quantexa",
    "ComplyAdvantage",
    "LexisNexis Risk",
    "NICE Actimize",
    "Actimize",
    "Pega",
    "FIS",
    "Moody's",
    "S&P Global",
    "Oracle",
    "Appian",
    "Dow Jones",
    "Napier",
    "Trulioo",
    "Onfido",
    "Sumsub",
    "Veriff",
    "Feedzai",
    "Socure",
    "Kyckr",
    "KYC360",
    "Ripjar",
    "FinScan",
    "IMTF",
    "Saphyre",
    "SymphonyAI",
    "Alloy",
    "Incode",
    "Norbloc",
    "smartKYC",
    "KYC Portal",
    "Encompass",
    "Sigma360",
    "Davies",
    # Niche RegTech / Compliance vendors
    "FullCircl",
    "Northrow",
    "CleverChain",
    "Muinmos",
    "Acuris",
    "Creditsafe",
    "iProov",
    "ComplyCube",
    "Jumio",
    "IDnow",
    "Resistant AI",
    "Featurespace",
    "Silent Eight",
    "ThetaRay",
    "Sardine",
    "Lucinity",
    "Sanction Scanner",
    "Cube",
    "Corlytics",
    "Behavox",
    "Taina",
    "BioCatch",
    "SEON",
    "Themis",
    "eflow",
    "SteelEye",
    "FundApps",
    "Kaizen Reporting",
    "Droit",
    "Elliptic",
    "Chainalysis",
    "TRM Labs",
    "Notabene",
    "RuleGuard",
    "Model Office",
    "Apiax",
    "Smarsh",
    "Konsentus",
    "Banfico",
    "Salt Edge",
    "Diligent",
    "KI Insurance",
    "Green Swan",
    "ShieldFC",
    "Whispli",
    "Regnology",
    "Athennian",
    "Scorechain",
    "Crystal Intelligence",
    # FS consultancies / recruiters / contract-heavy sources
    "Deloitte",
    "Eames Consulting",
    "VirtueTech Recruitment Group",
    "May Business Consulting",
    "Izertis",
    "Referment",
    "Miryco",
    "Hunter Bond",
    "Alexander Ash",
    "McGregor Boyall",
    "Huxley",
    "La Fosse",
    "Cornwallis Elt",
    "Harrington Starr",
    "Robert Walters",
    "Michael Page",
    "Investigo",
    "Oliver James",
    "Twenty84",
    "Randstad Digital",
    "Experis",
    "Adecco",
    "Airswift",
    "Anson McCade",
    "Pontoon",
    "TEKsystems",
    "Sanderson",
    "Lorien",
    "Harvey Nash",
    "Ntrinsic",
    "Mthree",
    "FDM Group",
    "Capco",
    "Capgemini Invent",
    "Accenture",
    "Publicis Sapient",
    "Cognizant",
    "EPAM",
    "Endava",
    "BJSS",
    "Kainos",
    "Slalom",
    "PA Consulting",
    "North Highland",
    "Baringa",
    "Delta Capita",
    "Ruleguard",
    # Asset servicing / client lifecycle adjacent
    "SS&C",
    "SS&C Technologies",
    "FNZ",
    "SEI",
    "Broadridge",
    "Euroclear",
    "Clearstream",
    "ICE",
    "Intercontinental Exchange",
    "SIX",
    "Apex Group",
    "TMF Group",
    "Alter Domus",
    "IQ-EQ",
    "Ocorian",
    "Aztec Group",
    "Waystone",
    "Apex Fintech Solutions",
    # Big Tech
    "Google",
    "Microsoft",
    "Amazon",
    "Apple",
    "Meta",
    "Salesforce",
    "Oracle",
    "SAP",
]

SEARCH_LOCATIONS = [
    "London, United Kingdom",
    "United Kingdom",
    "Remote",
]

EXCLUDE_LOCATION_TERMS = {
    "canada",
    "united states",
    "usa",
    "u.s.",
    "australia",
    "new zealand",
    "singapore",
    "hong kong",
    "india",
    "pakistan",
    "philippines",
    "malaysia",
    "thailand",
    "south africa",
    "nigeria",
    "kenya",
    "rwanda",
    "germany",
    "france",
    "spain",
    "italy",
    "netherlands",
    "belgium",
    "switzerland",
    "sweden",
    "norway",
    "denmark",
    "finland",
    "poland",
    "romania",
    "bulgaria",
    "austria",
    "portugal",
    "ireland",
}

EXCLUDE_TITLE_TERMS = {"growth"}
EXCLUDE_COMPANIES = {
    "bvnk",
    "checkout",
    "checkout.com",
    "complyadvantage",
    "ebury",
    "fenergo",
    "jp morgan",
    "jpm",
    "jpmorgan",
    "jpmorgan chase",
    "jpmorgan chase & co",
    "marks sattin",
    "wise",
    "wise payments",
    "wise plc",
    "wise inc",
    "wise ltd",
    "wise business",
    "wise platform",
    "transferwise",
    "transferwise ltd",
}

ROLE_TITLE_REQUIREMENTS = {
    "manager",
    "owner",
    "lead",
    "principal",
    "head",
    "director",
    "specialist",
    "analyst",
    "architect",
    "strategy",
    "operations",
    "management",
    "vp",
    "officer",
}

VENDOR_COMPANIES = {
    "fenergo",
    "complyadvantage",
    "quantexa",
    "lexisnexis",
    "nice actimize",
    "actimize",
    "pega",
    "oracle",
    "fis",
    "moody",
    "s&p global",
    "appian",
    "kyc360",
    "ripjar",
    "symphonyai",
    "saphyre",
    "encompass",
    "napier",
    "bridger",
    "dow jones",
    "alloy",
    "onfido",
    "trulioo",
    "sumsub",
    "veriff",
    "socure",
    "experian",
    "kyckr",
    "entrust",
    "finscan",
    "imtf",
    "norbloc",
    "smartkyc",
    "kyc portal",
    # KYC/CLM/KYB
    "fullcircl",
    "northrow",
    "cleverchain",
    "muinmos",
    "acuris",
    "creditsafe",
    # Identity Verification
    "iproov",
    "complycube",
    "jumio",
    "idnow",
    "resistant ai",
    # AML/Transaction Monitoring
    "featurespace",
    "silent eight",
    "thetaray",
    "sardine",
    "lucinity",
    "sanction scanner",
    # Regulatory Intelligence
    "cube",
    "corlytics",
    "behavox",
    "taina",
    # Fraud Prevention
    "biocatch",
    "seon",
    "feedzai",
    "themis",
    # Trade Surveillance / Market Abuse
    "eflow",
    "steeleye",
    "fundapps",
    "kaizen reporting",
    "droit",
    # Crypto / Digital Asset Compliance
    "elliptic",
    "chainalysis",
    "trm labs",
    "notabene",
    # GRC Platforms
    "ruleguard",
    "model office",
    "apiax",
    "smarsh",
    # Open Banking / PSD2
    "konsentus",
    "banfico",
    "salt edge",
    # Corporate Entity / Whistleblowing
    "diligent",
    "ki insurance",
    "green swan",
    # eComms / Conduct Surveillance
    "shieldfc",
    "whispli",
    # Additional niche
    "regnology",
    "athennian",
    "scorechain",
    "crystal intelligence",
}

FINTECH_COMPANIES = {
    "wise",
    "airwallex",
    "revolut",
    "monzo",
    "starling",
    "liberis",
    "lyst",
    "zego",
    "engine by starling",
    "visa",
    "mastercard",
    "worldpay",
    "checkout.com",
    "stripe",
    "modulr",
    "gocardless",
    "klarna",
    "n26",
    "tide",
    "mollie",
    "jpmorganchase",
    "goldman sachs",
    "marcus",
    "lseg",
    "broadridge",
    "davies",
    "experian",
    "socure",
    "kyckr",
    "quantexa",
    "complyadvantage",
    "plaid",
    "truelayer",
    "tink",
    "marqeta",
    "adyen",
    "rapyd",
    "curve",
    "chip",
    "kroo",
    "zopa",
    "oaknorth",
    "clearpay",
    "funding circle",
    "lendable",
    "zilch",
}

BANK_COMPANIES = {
    "barclays",
    "hsbc",
    "natwest",
    "lloyds",
    "lloyds banking group",
    "santander",
    "standard chartered",
    "citi",
    "jpmorgan",
    "goldman sachs",
    "morgan stanley",
    "bank of america",
    "deutsche bank",
    "ubs",
    "lseg",
    "nationwide",
    "tsb",
    "virgin money",
    "metro bank",
    "tesco bank",
    "coutts",
    "bnp paribas",
    "rbc",
    "ing",
    "rabobank",
    "abn amro",
    "unicredit",
}

TECH_COMPANIES = {
    "google",
    "microsoft",
    "amazon",
    "apple",
    "meta",
    "salesforce",
    "oracle",
    "sap",
    "servicenow",
    "atlassian",
}

DOMAIN_TERMS = [
    "kyc",
    "aml",
    "onboarding",
    "screening",
    "financial crime",
    "fincrime",
    "money laundering",
    "transaction monitoring",
    "perpetual kyc",
    "transformation",
    "remediation",
    "risk",
    "operational risk",
    "model risk",
    "regulatory change",
    "controls",
    "sanctions",
    "identity",
    "fraud",
    "compliance",
    "due diligence",
    "edd",
    "cdd",
    "kyb",
    "clm",
    "client lifecycle",
    "customer lifecycle",
    "account opening",
    "account onboarding",
    "client onboarding",
    "regulatory",
    "regtech",
    "case management",
    "investigation",
]

EXTRA_TERMS = [
    "api",
    "platform",
    "data",
    "analytics",
    "dashboard",
    "workflow",
    "orchestration",
    "decisioning",
    "rules",
    "configuration",
    "integration",
]

GAP_TERMS = {
    "lending": "Highlight any lending or credit lifecycle exposure.",
    "credit": "Highlight any credit decisioning or lending exposure.",
    "mobile": "Show any mobile UX or app product experience.",
    "consumer": "Emphasize consumer or retail onboarding if applicable.",
    "payments": "Show any payments or merchant onboarding experience.",
    "merchant": "Add any merchant onboarding or acquiring examples.",
    "ml": "Call out ML or model-driven risk tooling if relevant.",
    "machine learning": "Call out ML or model-driven risk tooling if relevant.",
    "data platform": "Emphasize data platform and data quality ownership.",
}

REASON_HINTS = {
    "onboarding": "Onboarding workflow ownership fits your KYC/onboarding platform delivery.",
    "kyc": "KYC domain aligns with your screening and compliance controls work.",
    "aml": "AML product experience aligns with your financial crime delivery.",
    "fraud": "Fraud prevention aligns with your screening-threshold optimization work.",
    "identity": "Identity verification aligns with your onboarding and risk controls background.",
    "case management": "Case management aligns with investigation and alert triage workflows.",
    "investigation": "Investigation workflow ownership aligns with your financial crime delivery.",
    "data": "Data and analytics product work aligns with your reporting dashboard builds.",
    "api": "Platform/API focus matches your integration and orchestration experience.",
    "clm": "Client lifecycle management aligns with your onboarding and screening background.",
    "client lifecycle": "Client lifecycle management aligns with your onboarding and screening background.",
    "customer lifecycle": "Customer lifecycle management aligns with your onboarding and screening background.",
    "account opening": "Account opening aligns with onboarding and journey design experience.",
    "kyb": "KYB exposure aligns with your complex entity onboarding experience.",
    "screening": "Screening and monitoring align with your financial crime controls work.",
}


def _dedupe_keep_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    deduped: list[str] = []
    for item in items:
        normalized = item.strip()
        key = normalized.lower()
        if not normalized or key in seen:
            continue
        seen.add(key)
        deduped.append(normalized)
    return deduped


# Discovery tiers deliberately cast a much wider net than the final email.
# Ranking/scoring then decides what is credible enough to surface.
TIER1_CORE_BOARD_KEYWORDS = [
    # KYC/KYB/CDD/EDD/CLM
    "kyc transformation",
    "kyc transformation lead",
    "kyc product owner",
    "kyc product manager",
    "kyb product owner",
    "kyb product manager",
    "cdd business analyst",
    "edd business analyst",
    "client lifecycle management",
    "client lifecycle transformation",
    "client transformation",
    "client onboarding transformation",
    "client operations transformation",
    "client service transformation",
    "client experience transformation",
    "client journey transformation",
    "client lifecycle business analyst",
    "client onboarding business analyst",
    "client transformation business analyst",
    "client onboarding transformation business analyst",
    "client operations transformation business analyst",
    "customer onboarding business analyst",
    "customer onboarding transformation",
    "customer transformation business analyst",
    "periodic review business analyst",
    "onboarding remediation",
    "kyc remediation",
    "fenergo business analyst",
    "fenergo product owner",
    "clm product owner",
    "clm business analyst",
    "obkyc business analyst",
    "obkyc transformation",
    # FinCrime product/change
    "financial crime product manager",
    "financial crime product owner",
    "financial crime business analyst",
    "financial crime business architect",
    "financial crime manager",
    "financial crime compliance manager",
    "payments financial crime manager",
    "financial crime manager payments",
    "financial crime transformation",
    "financial crime tom",
    "financial crime target operating model",
    "financial crime regulatory traceability",
    "financial crime change manager",
    "financial crime project manager",
    "financial crime programme manager",
    "aml product manager",
    "aml product owner",
    "aml business analyst",
    "aml compliance manager",
    "sanctions product manager",
    "sanctions business analyst",
    "sanctions screening product manager",
    "transaction monitoring product manager",
    "transaction monitoring business analyst",
    "trade surveillance business analyst",
    "trade surveillance product owner",
    "trade surveillance product manager",
    "screening product manager",
    "screening business analyst",
    "case management product manager",
    "case management business analyst",
    "fiu business analyst",
    "sar business analyst",
    "adverse media business analyst",
    "pep screening business analyst",
]

TIER2_ADJACENT_BOARD_KEYWORDS = [
    # Payments / regulated platform
    "payments product owner",
    "payments product manager",
    "payment operations business analyst",
    "payment systems business analyst",
    "payments transformation business analyst",
    "merchant onboarding product manager",
    "merchant onboarding business analyst",
    "acquiring product manager",
    "open banking product manager",
    "open banking business analyst",
    "fx payments product owner",
    "reconciliations business analyst",
    "settlements business analyst",
    "treasury platform business analyst",
    "platform transformation business analyst",
    # Regulatory / controls / data
    "regulatory change business analyst",
    "regulatory transformation business analyst",
    "controls business analyst",
    "control design business analyst",
    "risk controls business analyst",
    "risk transformation business analyst",
    "data lineage business analyst",
    "data quality business analyst",
    "cde business analyst",
    "regulatory reporting business analyst",
    "mi reporting business analyst",
    "workflow business analyst",
    "rules engine product manager",
    "decisioning product manager",
    "client data transformation business analyst",
    "client platform transformation business analyst",
    "client services transformation manager",
    "client operations change manager",
    # Wealth / asset servicing
    "wealth management business analyst",
    "wealth platform transformation",
    "wealth platform business analyst",
    "asset management business analyst",
    "asset management platform transformation",
    "fund onboarding business analyst",
    "investor onboarding business analyst",
    "transfer agency business analyst",
    "fund administration business analyst",
    "private banking onboarding business analyst",
]

TIER3_EXPLORATORY_BOARD_KEYWORDS = [
    "business architect banking",
    "business architect financial services",
    "transformation lead banking",
    "transformation manager financial services",
    "target operating model business analyst",
    "tom design business analyst",
    "operating model business analyst",
    "regulatory traceability business analyst",
    "regulatory control alignment business analyst",
    "control traceability business analyst",
    "business process improvement consultant client onboarding",
    "lean process client onboarding",
    "crm data transformation business analyst",
    "client transformation manager",
    "client change manager",
    "client operations manager transformation",
    "client services operating model",
    "salesforce customer onboarding",
    "salesforce financial services cloud business analyst",
    "servicenow workflow business analyst",
    "dynamics crm business analyst banking",
    "identity verification product manager",
    "identity platform product owner",
    "fraud prevention product manager",
    "fraud risk product owner",
    "product manager risk fraud",
    "risk fraud product manager",
    "risk and fraud product manager",
    "authentication product manager",
    "risk platform product manager",
    "compliance platform product manager",
]

DOMAIN_TERMS = _dedupe_keep_order(
    DOMAIN_TERMS
    + [
        "payments",
        "payment operations",
        "merchant onboarding",
        "acquiring",
        "open banking",
        "fx",
        "reconciliations",
        "settlements",
        "treasury",
        "regulatory reporting",
        "data lineage",
        "data quality",
        "cde",
        "mi reporting",
        "target operating model",
        "tom",
        "client transformation",
        "client onboarding transformation",
        "client operations transformation",
        "client service transformation",
        "client experience transformation",
        "client journey transformation",
        "client data transformation",
        "client platform transformation",
        "client services operating model",
        "salesforce",
        "servicenow",
        "dynamics",
        "periodic review",
        "remediation",
        "obkyc",
        "fiu",
        "sar",
        "adverse media",
        "pep",
        "trade surveillance",
        "market abuse",
        "regulatory traceability",
        "control alignment",
        "control traceability",
        "lean process",
        "business process improvement",
        "wealth management",
        "wealth platform",
        "asset management",
        "asset management platform",
        "fund onboarding",
        "investor onboarding",
        "transfer agency",
        "fund administration",
    ]
)

EXTRA_TERMS = _dedupe_keep_order(
    EXTRA_TERMS
    + [
        "migration",
        "data mapping",
        "data model",
        "lineage",
        "controls testing",
        "control design",
        "target operating model",
        "case workflow",
        "client journey",
        "client operations",
        "client services",
        "client data",
        "client platform",
        "screening hits",
        "alert triage",
        "rules engine",
        "decision engine",
        "obkyc",
        "trade surveillance",
        "market abuse",
        "regulatory traceability",
        "control alignment",
        "control traceability",
        "target-state process",
        "as-is process",
        "to-be process",
        "process improvement",
    ]
)

GAP_TERMS.update(
    {
        "reconciliations": "Emphasize platform controls, operational process redesign, and payments data quality.",
        "settlements": "Show payments, operations, and control-design experience.",
        "regulatory reporting": "Highlight regulatory change, MI, controls, and stakeholder governance.",
        "wealth management": "Bridge from CLM/onboarding into private banking, investor onboarding, or regulated client lifecycle.",
        "asset management": "Bridge from CLM/onboarding into fund/investor onboarding and regulated operations.",
        "salesforce": "Use the Salesforce-to-Fenergo migration and CRM/data-mapping examples.",
        "servicenow": "Position workflow/case-management delivery and operational control design.",
        "client transformation": "Lead with Vistra: global CLM/onboarding transformation across jurisdictions, workflow redesign, and platform governance.",
        "client onboarding transformation": "Lead with Vistra client onboarding transformation, Fenergo/Napier/Enate integration, and cycle-time improvement.",
        "client operations transformation": "Position the Vistra operating-model and workflow redesign work as client-operations transformation.",
        "client services operating model": "Use the Vistra TOM, jurisdictional workflow and client-servicing handoff examples.",
        "obkyc": "Use Fenergo/CLM onboarding workflow experience and bank-grade requirements/process-mapping examples.",
        "trade surveillance": "Bridge from financial-crime controls, alert workflow, governance and compliance technology into surveillance change.",
        "regulatory traceability": "Emphasize requirements traceability, control alignment, governance and regulated delivery evidence.",
        "lean process": "Use Vistra workflow redesign, onboarding cycle-time improvement and operational handoff examples.",
    }
)

REASON_HINTS.update(
    {
        "payments": "Payments roles connect to your regulated platform, onboarding, API and controls experience.",
        "reconciliations": "Reconciliation work overlaps with control design, data quality and regulated workflow ownership.",
        "regulatory reporting": "Regulatory reporting aligns with your compliance platform, MI and control evidence experience.",
        "data lineage": "Data-lineage work aligns with your data-model, migration and controls background.",
        "salesforce": "Salesforce transformation links directly to your Salesforce-to-Fenergo migration experience.",
        "client transformation": "Client transformation links directly to your Vistra CLM/onboarding programme across 30+ jurisdictions.",
        "client onboarding transformation": "Client onboarding transformation is a direct Vistra fit: global onboarding redesign, Fenergo/Napier/Enate and measurable cycle-time improvement.",
        "client operations transformation": "Client operations transformation aligns with your Vistra workflow, TOM and operational control redesign work.",
        "client journey": "Client journey work aligns with onboarding, CLM and regulated workflow design.",
        "wealth management": "Wealth roles overlap with client onboarding, lifecycle controls and regulated operations.",
        "asset management": "Asset-management roles overlap with investor onboarding, operations and regulatory control delivery.",
        "obkyc": "OBKYC is a direct CLM/onboarding workflow fit from your Fenergo and multi-jurisdiction onboarding work.",
        "trade surveillance": "Trade-surveillance roles overlap with financial-crime monitoring, alert workflow and compliance technology delivery.",
        "regulatory traceability": "Regulatory traceability aligns with your requirements, governance, controls and audit-evidence delivery.",
        "lean process": "Lean/process-improvement roles connect to your Vistra onboarding redesign and measurable cycle-time improvements.",
        "fiu": "FIU workflow roles align with alert triage, SAR escalation and financial-crime case management.",
        "sar": "SAR workflow roles align with financial-crime investigation and escalation process design.",
    }
)

SEARCH_KEYWORDS = _dedupe_keep_order(
    SEARCH_KEYWORDS
    + TIER1_CORE_BOARD_KEYWORDS
    + TIER2_ADJACENT_BOARD_KEYWORDS
    + TIER3_EXPLORATORY_BOARD_KEYWORDS
)

BOARD_KEYWORDS = _dedupe_keep_order(BOARD_KEYWORDS + TIER1_CORE_BOARD_KEYWORDS)
BROAD_BOARD_KEYWORDS = _dedupe_keep_order(
    BROAD_BOARD_KEYWORDS + TIER2_ADJACENT_BOARD_KEYWORDS + TIER3_EXPLORATORY_BOARD_KEYWORDS
)
COMPANY_SEARCH_TERMS = _dedupe_keep_order(
    COMPANY_SEARCH_TERMS
    + TIER1_CORE_BOARD_KEYWORDS[:30]
    + TIER2_ADJACENT_BOARD_KEYWORDS[:25]
    + TIER3_EXPLORATORY_BOARD_KEYWORDS[:15]
)
