SEARCH_KEYWORDS = [
    "product manager kyc",
    "product manager aml",
    "product manager onboarding",
    "product manager screening",
    "product manager financial crime",
    "product manager compliance",
    "product manager identity",
    "product manager fraud",
    "product manager regtech",
    "product manager kyb",
    "product manager cdd",
    "product manager edd",
    "product owner kyc",
    "product owner onboarding",
    "product owner compliance",
    "product owner screening",
    "product manager transaction monitoring",
    "product manager client onboarding",
    "product manager customer onboarding",
    "product manager account opening",
    "product manager client lifecycle",
    "product manager customer lifecycle",
    "product manager clm",
    "product lead risk",
    "product lead compliance",
    "product manager sanctions",
    "product manager due diligence",
    "product manager case management",
    "product manager investigation",
    "product manager fraud prevention",
    "product manager identity verification",
    "product manager onboarding platform",
    "product manager compliance platform",
    "product manager risk platform",
    "product manager screening platform",
    "product manager financial crime platform",
    "client lifecycle management",
    "client lifecycle manager",
    "customer lifecycle management",
    "clm manager",
    "client lifecycle operations",
    "client lifecycle operations lead",
    "customer lifecycle operations",
    "customer lifecycle operations lead",
    "client lifecycle product",
    "customer lifecycle product",
    "onboarding operations",
    "onboarding operations lead",
    "client onboarding operations",
    "customer onboarding operations",
    "operations strategy",
    "operations strategy manager",
    "operations strategy lead",
    "operating model",
    "operating model design",
    "operating model manager",
    "operating model lead",
    "process owner",
    "customer onboarding lead",
    "client onboarding lead",
    "kyc operations lead",
    "aml operations lead",
    "compliance operations lead",
    "financial crime operations",
    "financial crime operations manager",
    "risk operations manager",
    "regulatory operations manager",
    "business analyst kyc",
    "business analyst aml",
    "business analyst onboarding",
    "business analyst compliance",
    "business analyst financial crime",
    "lead business analyst",
    "senior business analyst",
    "principal business analyst",
    "product business analyst",
    "process owner onboarding",
    "process owner kyc",
    "process owner compliance",
    "client lifecycle analyst",
    "customer lifecycle analyst",
]

BOARD_KEYWORDS = [
    "product manager onboarding",
    "product manager kyc",
    "product manager aml",
    "product manager compliance",
    "product manager screening",
    "product owner onboarding",
    "product manager fraud",
    "product manager financial crime",
    "client lifecycle management",
    "customer lifecycle management",
    "operations strategy",
    "onboarding operations",
    "client onboarding operations",
    "customer onboarding operations",
    "process owner",
    "operating model",
    "business analyst kyc",
    "business analyst onboarding",
    "lead business analyst",
    "process owner onboarding",
]

BROAD_BOARD_KEYWORDS = [
    "product manager",
    "product owner",
    "product lead",
    "product director",
    "product operations",
    "operations strategy",
    "onboarding operations",
    "client onboarding operations",
    "customer onboarding operations",
    "operating model",
    "process owner",
    "client lifecycle manager",
    "customer lifecycle manager",
    "business analyst",
    "lead business analyst",
    "senior business analyst",
    "process owner",
]

COMPANY_SEARCH_TERMS = [
    "product manager",
    "product owner",
    "product lead",
    "product manager onboarding",
    "product manager compliance",
    "product manager risk",
    "product manager fraud",
    "product management",
    "product operations",
    "product specialist",
    "client lifecycle",
    "customer lifecycle",
    "clm",
    "client lifecycle management",
    "customer lifecycle management",
    "onboarding operations",
    "client onboarding operations",
    "customer onboarding operations",
    "operations strategy",
    "operating model",
    "process owner",
    "financial crime operations",
    "compliance operations",
    "business analyst",
    "lead business analyst",
    "senior business analyst",
    "principal business analyst",
    "process owner",
]

SEARCH_COMPANIES = [
    # Banks & FS
    "Barclays",
    "HSBC",
    "NatWest",
    "Lloyds",
    "Lloyds Banking Group",
    "Santander",
    "Nationwide",
    "TSB",
    "Virgin Money",
    "Metro Bank",
    "Tesco Bank",
    "Coutts",
    "Standard Chartered",
    "Citi",
    "JPMorgan",
    "JPMorgan Chase",
    "JPMorgan Chase & Co",
    "Goldman Sachs",
    "Morgan Stanley",
    "Bank of America",
    "Deutsche Bank",
    "UBS",
    "BNP Paribas",
    "Société Générale",
    "Societe Generale",
    "Crédit Agricole",
    "Credit Agricole",
    "RBC",
    "ING",
    "Rabobank",
    "ABN AMRO",
    "UniCredit",
    "BNY Mellon",
    "State Street",
    "Northern Trust",
    "BlackRock",
    "Vanguard",
    "Fidelity",
    "Nomura",
    "Mizuho",
    "MUFG",
    "SMBC",
    "Macquarie",
    "Jefferies",
    "Rothschild",
    "LSEG",
    # Fintech / Payments
    "Wise",
    "Revolut",
    "Monzo",
    "Starling",
    "Engine by Starling",
    "Tide",
    "Zopa",
    "OakNorth",
    "Atom Bank",
    "ClearBank",
    "Kroo",
    "Chip",
    "Curve",
    "Checkout.com",
    "Stripe",
    "Adyen",
    "Worldpay",
    "GoCardless",
    "Modulr",
    "TrueLayer",
    "Tink",
    "Plaid",
    "Airwallex",
    "Rapyd",
    "Marqeta",
    "Mambu",
    "Thought Machine",
    "Temenos",
    "Avaloq",
    "Funding Circle",
    "Lendable",
    "Zilch",
    "Solaris",
    "Soldo",
    "Pleo",
    "Yapily",
    "PayPal",
    "Block",
    "Square",
    # RegTech / KYC / Screening
    "Fenergo",
    "Quantexa",
    "ComplyAdvantage",
    "LexisNexis Risk",
    "NICE Actimize",
    "Actimize",
    "Pega",
    "FIS",
    "Moody's",
    "S&P Global",
    "Oracle",
    "Appian",
    "Dow Jones",
    "Napier",
    "Trulioo",
    "Onfido",
    "Sumsub",
    "Veriff",
    "Feedzai",
    "Socure",
    "Kyckr",
    "KYC360",
    "Ripjar",
    "FinScan",
    "IMTF",
    "Saphyre",
    "SymphonyAI",
    "Alloy",
    "Incode",
    "Norbloc",
    "smartKYC",
    "KYC Portal",
    "Encompass",
    "Sigma360",
    "Davies",
    # Big Tech
    "Google",
    "Microsoft",
    "Amazon",
    "Apple",
    "Meta",
    "Salesforce",
    "Oracle",
    "SAP",
]

SEARCH_LOCATIONS = [
    "London, United Kingdom",
    "United Kingdom",
    "Remote",
]

EXCLUDE_LOCATION_TERMS = {
    "canada",
    "united states",
    "usa",
    "u.s.",
    "australia",
    "new zealand",
    "singapore",
    "hong kong",
    "india",
    "pakistan",
    "philippines",
    "malaysia",
    "thailand",
    "south africa",
    "nigeria",
    "kenya",
    "rwanda",
    "germany",
    "france",
    "spain",
    "italy",
    "netherlands",
    "belgium",
    "switzerland",
    "sweden",
    "norway",
    "denmark",
    "finland",
    "poland",
    "romania",
    "bulgaria",
    "austria",
    "portugal",
    "ireland",
}

EXCLUDE_TITLE_TERMS = {"growth"}
EXCLUDE_COMPANIES = {"ebury"}

ROLE_TITLE_REQUIREMENTS = {
    "manager",
    "owner",
    "lead",
    "principal",
    "head",
    "director",
    "specialist",
    "analyst",
    "architect",
    "strategy",
    "operations",
    "management",
    "vp",
}

VENDOR_COMPANIES = {
    "fenergo",
    "complyadvantage",
    "quantexa",
    "lexisnexis",
    "nice actimize",
    "actimize",
    "pega",
    "oracle",
    "fis",
    "moody",
    "s&p global",
    "appian",
    "kyc360",
    "ripjar",
    "symphonyai",
    "saphyre",
    "encompass",
    "napier",
    "bridger",
    "dow jones",
    "alloy",
    "onfido",
    "trulioo",
    "sumsub",
    "veriff",
    "socure",
    "experian",
    "kyckr",
    "entrust",
    "finscan",
    "imtf",
    "norbloc",
    "smartkyc",
    "kyc portal",
}

FINTECH_COMPANIES = {
    "wise",
    "airwallex",
    "revolut",
    "monzo",
    "starling",
    "engine by starling",
    "visa",
    "mastercard",
    "worldpay",
    "checkout.com",
    "stripe",
    "modulr",
    "gocardless",
    "klarna",
    "n26",
    "tide",
    "mollie",
    "jpmorganchase",
    "goldman sachs",
    "marcus",
    "lseg",
    "broadridge",
    "davies",
    "experian",
    "socure",
    "kyckr",
    "quantexa",
    "complyadvantage",
    "plaid",
    "truelayer",
    "tink",
    "marqeta",
    "adyen",
    "rapyd",
    "curve",
    "chip",
    "kroo",
    "zopa",
    "oaknorth",
    "clearpay",
    "funding circle",
    "lendable",
    "zilch",
}

BANK_COMPANIES = {
    "barclays",
    "hsbc",
    "natwest",
    "lloyds",
    "lloyds banking group",
    "santander",
    "standard chartered",
    "citi",
    "jpmorgan",
    "goldman sachs",
    "morgan stanley",
    "bank of america",
    "deutsche bank",
    "ubs",
    "lseg",
    "nationwide",
    "tsb",
    "virgin money",
    "metro bank",
    "tesco bank",
    "coutts",
    "bnp paribas",
    "rbc",
    "ing",
    "rabobank",
    "abn amro",
    "unicredit",
}

TECH_COMPANIES = {
    "google",
    "microsoft",
    "amazon",
    "apple",
    "meta",
    "salesforce",
    "oracle",
    "sap",
    "servicenow",
    "atlassian",
}

DOMAIN_TERMS = [
    "kyc",
    "aml",
    "onboarding",
    "screening",
    "financial crime",
    "transaction monitoring",
    "sanctions",
    "identity",
    "fraud",
    "compliance",
    "due diligence",
    "edd",
    "cdd",
    "kyb",
    "clm",
    "client lifecycle",
    "customer lifecycle",
    "account opening",
    "account onboarding",
    "client onboarding",
    "regulatory",
    "regtech",
    "case management",
    "investigation",
]

EXTRA_TERMS = [
    "api",
    "platform",
    "data",
    "analytics",
    "dashboard",
    "workflow",
    "orchestration",
    "decisioning",
    "rules",
    "configuration",
    "integration",
]

GAP_TERMS = {
    "lending": "Highlight any lending or credit lifecycle exposure.",
    "credit": "Highlight any credit decisioning or lending exposure.",
    "mobile": "Show any mobile UX or app product experience.",
    "consumer": "Emphasize consumer or retail onboarding if applicable.",
    "payments": "Show any payments or merchant onboarding experience.",
    "merchant": "Add any merchant onboarding or acquiring examples.",
    "ml": "Call out ML or model-driven risk tooling if relevant.",
    "machine learning": "Call out ML or model-driven risk tooling if relevant.",
    "data platform": "Emphasize data platform and data quality ownership.",
}

REASON_HINTS = {
    "onboarding": "Onboarding workflow ownership fits your KYC/onboarding platform delivery.",
    "kyc": "KYC domain aligns with your screening and compliance controls work.",
    "aml": "AML product experience aligns with your financial crime delivery.",
    "fraud": "Fraud prevention aligns with your screening-threshold optimization work.",
    "identity": "Identity verification aligns with your onboarding and risk controls background.",
    "case management": "Case management aligns with investigation and alert triage workflows.",
    "investigation": "Investigation workflow ownership aligns with your financial crime delivery.",
    "data": "Data and analytics product work aligns with your reporting dashboard builds.",
    "api": "Platform/API focus matches your integration and orchestration experience.",
    "clm": "Client lifecycle management aligns with your onboarding and screening background.",
    "client lifecycle": "Client lifecycle management aligns with your onboarding and screening background.",
    "customer lifecycle": "Customer lifecycle management aligns with your onboarding and screening background.",
    "account opening": "Account opening aligns with onboarding and journey design experience.",
    "kyb": "KYB exposure aligns with your complex entity onboarding experience.",
    "screening": "Screening and monitoring align with your financial crime controls work.",
}
